Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Metrics/AbcSize:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/ColonMethodCall:
  Exclude:
    - 'app/models/concerns/post_view.rb'

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
