default: &default
  access_key_id:     <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_ACCESS_SECRET'] %>
  s3_host_name:      <%= ENV['AWS_S3_HOST_NAME'] %>
  bucket:            <%= ENV['AWS_S3_BUCKET'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
