# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 124be943276622c10a768d1f29675d55fb7dfa290b70d3ec5d0cdc27d529c481434766fecd61bd0bb8f1dc2efbca2d2e132dd05c8afdd1c29fbd70fae2074753

test:
  secret_key_base: 0fd3bc52e2d5e27e65be489a848b1e9a75e93d6f6558d55697eb2efbf90b2d62daaf448aa636a97887b534baa65d3ce75a6fcfa961dcb18a82f63b288579d07a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
